version: '3.8'
services:
    app:  # This is the PHP-FPM container
        build:
            context: .
            target: development # Or production, for the production build
        volumes:
            - .:/var/www:delegated  # Mount the project directory (for development)
        depends_on:
            - db
        healthcheck:
            test: [ "CMD", "php-fpm", "-t" ] # Test if php-fpm config is valid
            interval: 10s
            timeout: 5s
            retries: 3
        environment:
            - APP_ENV=local  # Or production
            - DB_HOST=db
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        env_file:
            - .env

    nginx: # This is the Nginx container
        image: drmartinel/nginxbookverse:v1.0.0
        ports:
            - "80:80"
        depends_on:
            - app

    db: #MySQL Database
        image: mysql:8.0
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        env_file:
            - .env.db

volumes:
    db_data:
