version: '3.8'
services:
    app:  # This is the PHP-FPM container
        build:
            context: .
            target: development # Or production, for the production build
        volumes:
            - .:/var/www:delegated  # Mount the project directory (for development)
        depends_on:
            - db
        healthcheck:
            test: [ "CMD", "php-fpm", "-t" ] # Test if php-fpm config is valid
            interval: 10s
            timeout: 5s
            retries: 3
        environment:
            - APP_ENV=local  # Or production
            - DB_HOST=db
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - REVERB_HOST=reverb
            - REVERB_PORT=8080
            - REVERB_SCHEME=http
        env_file:
            - .env

    nginx: # This is the Nginx container
        image: nginx:stable-alpine  # Use the official Nginx image
        ports:
            - "80:80"   # Map port 80 on the host to port 80 in the container
        volumes:
            - .:/var/www:delegated # Mount the project directory (for serving static assets)
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro # Mount the Nginx config file (read-only)
        depends_on:
            - app     # Nginx depends on the PHP-FPM container

    db: #MySQL Database
        image: mysql:8.0
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        env_file:
            - .env.db

    reverb:
        build:
            context: .
            dockerfile: Dockerfile.reverb
        ports:
            - "8080:8080"
        environment:
            - APP_KEY=${REVERB_APP_KEY}
            - APP_SECRET=${REVERB_APP_SECRET}
            - PORT=8080
        depends_on:
            - app
        env_file:
            - .env
        restart: unless-stopped

volumes:
    db_data:
